api_key = "Your API Key"
organization_name = "Your Org Name"
splunk_webhook_name = "Splunk-Webhook"
splunk_webhook_url = "https://YourSpunkUrl:443/services/collector/raw"
splunk_webhook_auth = "YourSharedSecret"